spring.application.name=lego-ms-reviews-jj

server.port=8087

# ORACLE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@g6ytlgeqbkddeysn_high?TNS_ADMIN=/Users/pepemarcet/Desktop/Wallet_G6YTLGEQBKDDEYSN
spring.datasource.username=ADMIN
spring.datasource.password=JoseIgnacioMarcet11.

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.open-in-view=false

# EUREKA OFF
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false