# --- CONFIGURACIÓN BÁSICA ---
spring.application.name=api-gateway
server.port=8080

# --- CONEXIÓN EUREKA ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# --- CONFIGURACIÓN DE RUTAS (Sintaxis MVC Explícita) ---

# 1. Catálogo
spring.cloud.gateway.mvc.routes[0].id=catalogo-service
spring.cloud.gateway.mvc.routes[0].uri=lb://catalogo-jj
spring.cloud.gateway.mvc.routes[0].predicates[0].name=Path
spring.cloud.gateway.mvc.routes[0].predicates[0].args[patterns]=/api/catalogo/**

# 2. Pagos
spring.cloud.gateway.mvc.routes[1].id=pago-service
spring.cloud.gateway.mvc.routes[1].uri=lb://pago-jj
spring.cloud.gateway.mvc.routes[1].predicates[0].name=Path
spring.cloud.gateway.mvc.routes[1].predicates[0].args[patterns]=/api/pagos/**

# 3. Inventario
spring.cloud.gateway.mvc.routes[2].id=inventario-service
spring.cloud.gateway.mvc.routes[2].uri=lb://inventario-jj
spring.cloud.gateway.mvc.routes[2].predicates[0].name=Path
spring.cloud.gateway.mvc.routes[2].predicates[0].args[patterns]=/api/inventario/**

# 4. Envío
spring.cloud.gateway.mvc.routes[3].id=envio-service
spring.cloud.gateway.mvc.routes[3].uri=lb://envio-jj
spring.cloud.gateway.mvc.routes[3].predicates[0].name=Path
spring.cloud.gateway.mvc.routes[3].predicates[0].args[patterns]=/api/envios/**

# 5. Usuarios
spring.cloud.gateway.mvc.routes[4].id=usuario-service
spring.cloud.gateway.mvc.routes[4].uri=lb://usuario-jj
spring.cloud.gateway.mvc.routes[4].predicates[0].name=Path
spring.cloud.gateway.mvc.routes[4].predicates[0].args[patterns]=/api/usuarios/**

# 6. Autenticación
spring.cloud.gateway.mvc.routes[5].id=auth-service
spring.cloud.gateway.mvc.routes[5].uri=lb://auth-jj
spring.cloud.gateway.mvc.routes[5].predicates[0].name=Path
spring.cloud.gateway.mvc.routes[5].predicates[0].args[patterns]=/api/auth/**

# --- CONFIGURACIÓN DE TIMEOUTS (Opcional pero Recomendado) ---
# Evita que las peticiones mueran si Oracle Cloud tarda un poco en responder
spring.cloud.gateway.mvc.http-client.connect-timeout=5000
spring.cloud.gateway.mvc.http-client.read-timeout=5000