spring.application.name=api-gateway

server.port=8080


# Conexión Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/



# --- CONFIGURACIÓN DE RUTAS ---

# 1. Ruta para Catálogo
spring.cloud.gateway.routes[0].id=catalogo-service
spring.cloud.gateway.routes[0].uri=lb://catalogo-jj
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/catalogo/**

# 2. Ruta para Pagos
spring.cloud.gateway.routes[1].id=pago-service
spring.cloud.gateway.routes[1].uri=lb://pago-jj
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/pagos/**

# 3. Ruta para Inventario
spring.cloud.gateway.routes[2].id=inventario-service
spring.cloud.gateway.routes[2].uri=lb://inventario-jj
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/inventario/**

# 4. Ruta para Envío
spring.cloud.gateway.routes[3].id=envio-service
spring.cloud.gateway.routes[3].uri=lb://envio-jj
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/envios/**