# 1. Identificación del Microservicio (IE 1.2.1)
spring.application.name=inventario-jj
server.port=8082

# 2. Configuración de Base de Datos MySQL - XAMPP (IE 2.1.2)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@g6ytlgeqbkddeysn_high?TNS_ADMIN=C:/Users/romer/OneDrive/Desktop/Proyecto_Test
spring.datasource.username=usr_inventariojj
spring.datasource.password=Duocuc12345.
logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.java.sql=DEBUG

# 3. Configuración de JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# 4. Registro en Eureka Server (IE 2.4.2)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1




